GliefIntegration/force-app/main/default/objects/LegalEntity__c/LegalEntity__c.object-meta.xml
<CustomObject>
    <label>Legal Entity</label>
    <nameField>
        <displayFormat>LE-{000000000}</displayFormat>
        <label>Legal Entity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GliefIntegration/force-app/main/default/objects/LegalEntity__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LEICategory</valueSetName>
    </valueSet>
</CustomField>

GliefIntegration/force-app/main/default/objects/LegalEntity__c/fields/Jurisdiction__c.field-meta.xml
<CustomField>
    <fullName>Jurisdiction__c</fullName>
    <label>Jurisdiction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Jurisdiction</valueSetName>
    </valueSet>
</CustomField>

GliefIntegration/force-app/main/default/objects/LegalEntity__c/fields/LEI__c.field-meta.xml
<CustomField>
    <fullName>LEI__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Official LEI - external id - required and unique</description>
    <externalId>true</externalId>
    <label>LEI</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

GliefIntegration/force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0000000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GliefIntegration/force-app/main/default/globalValueSets/Jurisdiction.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>LU</fullName>
    </customValue>
    <customValue>
        <fullName>FI</fullName>
    </customValue>
    <masterLabel>Jurisdiction</masterLabel>
</GlobalValueSet>

GliefIntegration/force-app/main/default/globalValueSets/LEICategory.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>GENERAL</fullName>
    </customValue>
    <masterLabel>LEI Category</masterLabel>
</GlobalValueSet>

GliefIntegration/force-app/main/default/classes/LegalEntityBatchTest.cls
/**
 * @description       : 
 * @author            : Eleonore Pean
 * @group             : 
 * @last modified on  : 03-18-2025
 * @last modified by  : Eleonore Pean
**/
@isTest
public class LegalEntityBatchTest {
    
    @isTest
    static void testTriggerBatchExecutionWithMock() {
        // Utiliser un mock pour simuler la réponse API
        Test.setMock(HttpCalloutMock.class, 
            new LegalEntityCalloutMock(200, 
                '{"data":[{"attributes":{"lei":"1234567890ABCDEF","entity":{"legalName":{"name":"Test Entity"},"category":"GENERAL","jurisdiction":"LU","status":"ACTIVE"},"registration":{"status":"ISSUED","initialRegistrationDate":"2015-07-30T01:44:43Z","lastUpdateDate":"2024-07-12T12:59:07Z","nextRenewalDate":"2025-08-03T00:00:06Z"}}}]}')
        );

        Test.startTest();
        // Insert legalEntity to launch trigger
        LegalEntity__c entity = new LegalEntity__c(LEI__c = '1234567890ABCDEF');
        insert entity;
        // simulate end of batch
        Test.stopTest();

        // check that legal entity was updated by the batch
        LegalEntity__c updatedEntity = [SELECT LEI__c, Category__c FROM LegalEntity__c WHERE LEI__c = '1234567890ABCDEF' LIMIT 1];
        Assert.areNotEqual(null, updatedEntity.Category__c, 'LegalEntity should have been updated in the database');
    }

    @isTest
    static void testTriggerBatchExecutionWithMockInvalid() {
        // Utiliser un mock pour simuler la réponse API
        Test.setMock(HttpCalloutMock.class, 
            new LegalEntityCalloutMock(200, 
                '{"data":[{"attributes":{"lei":"1234567890ABCDEF09181","entity":{"legalName":{"name":"Test Entity"},"category":"GENERAL","jurisdiction":"LU","status":"ACTIVE"},"registration":{"status":"ISSUED","initialRegistrationDate":"2015-07-30T01:44:43Z","lastUpdateDate":"2024-07-12T12:59:07Z","nextRenewalDate":"2025-08-03T00:00:06Z"}}}]}')
        );

        Test.startTest();
        // Insert legalEntity to launch trigger
        LegalEntity__c entity = new LegalEntity__c(LEI__c = '1234567890ABCDEF09181');
        try {
            insert entity;
        } catch (DmlException e) {
            // Assert that the error message is related to LEI length validation
            System.assert(e.getMessage().contains('STRING_TOO_LONG'), 
                'Expected validation error for LEI length');
        }

        // check that legal entity was updated by the batch
        Assert.isTrue([SELECT LEI__c, Category__c FROM LegalEntity__c].isEmpty(), 'LegalEntity should not have been created in the database');
    }

    @isTest
    static void testUpdateWithInvalidPicklist() {

        Test.startTest();
        // Insert legalEntity to launch trigger
        LegalEntity__c entity = new LegalEntity__c(LEI__c = '1234567890ABCDEF', Jurisdiction__c = 'TESTKO');
        try {
            LegalEntityUpdater.upsertLegalEntity(new List<LegalEntity__c>{entity});
        } catch (DmlException e) {
            // Assert that the error message is related to LEI length validation
            System.assert(e.getMessage().contains('Picklist'), 
                'Expected validation error for invalid picklist');
        }

        // check that legal entity was updated by the batch
        Assert.isTrue([SELECT LEI__c, Category__c FROM LegalEntity__c WHERE LEI__c = :entity.LEI__c LIMIT 1].isEmpty(), 'LegalEntity should have been created in the database');
        Assert.isFalse([SELECT Id From Log__c].isEmpty(), 'Log__c should have been created');
    }
}